### ISSUE TITLE
Problem regarding the navigation bar 

### ISSUE THREAD

**Issue by Abbas-000** [creativecommons/certificates-landing-page-theme#1]
## Describe the bug

The navigation bar on the https://certificates.creativecommons.org/ does not function well on smaller screens. like on smaller screens the (registration and calendar) button is not visible when you click on the bars button as well as there is some more padding below the bars button.
## To Reproduce

1. Go to 'https://certificates.creativecommons.org/' using smaller screen devices
2. Click on 'bars' button on the navigation bar. (registration and calendar) button is not visible.
3. Scroll down to and you will see the bars button is not aligned at the center of the navigation bar.

## Expected behavior
The registration and calendar buttons should be visible on clicking the bars button on smaller screen devices and the bars button should be aligned at the center of the navigation bar not at the top.

## Screenshots
![issue-pic](https://user-images.githubusercontent.com/25281338/76182408-9fd30300-61e6-11ea-89fb-3198b338bfd1.PNG)

## Desktop (please complete the following information)
 - OS: Microsoft windows 10 Pro Education
 - Browser Chrome
 - Version Version 80.0.3987.132 (Official Build) (64-bit)

**Comment by hugosolar** [comment]
Hey @Abbas-000 
Since we're working on the redesign of this website, we're not planning to work on the current theme
